[package]
name = "gioco"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
bevy-inspector-egui = "0.28.1"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

